name: Build-All

on:
  push:
    branches-ignore:
      - main

  pull_request:
    branches:
      - main


jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - { name: 'Scala 2', version: "2.11.12", binary-version: "2.11", java-version: "11", java-distribution: "temurin", report: "" }
          - { name: 'Scala 2', version: "2.12.12", binary-version: "2.12", java-version: "11", java-distribution: "temurin", report: "" }
          - { name: 'Scala 2', version: "2.13.11", binary-version: "2.13", java-version: "11", java-distribution: "temurin", report: "report" }
          - { name: 'Scala 3', version: "3.0.0",   binary-version: "3",    java-version: "11", java-distribution: "temurin", report: "" }

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.scala.java-version }}
          distribution: ${{ matrix.scala.java-distribution }}
          cache: sbt
      - uses: sbt/setup-sbt@v1

      - name: "[Push] Build All for ${{ matrix.scala.name }}: ${{ matrix.scala.version }} - ${{ github.run_number }}"
        if: github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          CURRENT_BRANCH_NAME: ${{ github.ref }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
        run: |
          echo "[BEFORE]CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME}"
          export CURRENT_BRANCH_NAME="${CURRENT_BRANCH_NAME#refs/heads/}"
          echo " [AFTER]CURRENT_BRANCH_NAME=${CURRENT_BRANCH_NAME}"
          export CI_BRANCH=$CURRENT_BRANCH_NAME
          echo "CI_BRANCH: $CI_BRANCH"
          echo "RUN_ID=${RUN_ID}"
          echo "RUN_NUMBER=${RUN_NUMBER}"
          echo "Push #${PUSH_NUMBER}"
          java -version
          .github/workflows/sbt-build-all.sh ${{ matrix.scala.version }} ${{ matrix.scala.report }}
